import { Eye, Pencil, RotateCcw, Trash2 } from "lucide-react";
import type { SupplierAgreement } from "@/features/supplier-agreements/supplier-agreement.types";
import { formatSupplierAgreementCurrency, formatSupplierAgreementDate, SUPPLIER_AGREEMENT_STATUS_LABELS } from "@/features/supplier-agreements/supplier-agreement.utils";

interface Props { agreement: SupplierAgreement; vendorName: string; materialNames: string[]; isRestoring?: boolean; onDetails: (agreement: SupplierAgreement) => void; onEdit: (agreement: SupplierAgreement) => void; onDelete: (agreement: SupplierAgreement) => void; onRestore: (agreement: SupplierAgreement) => void }
export default function SupplierAgreementCard({ agreement, vendorName, materialNames, isRestoring = false, onDetails, onEdit, onDelete, onRestore }: Props) {
  const materials = materialNames.length ? materialNames.join(", ") : "Materials no longer active";
  return <article className={`min-w-0 rounded-2xl border p-4 shadow-sm ${agreement.isDeleted ? "border-destructive/30 bg-muted/40" : "border-border bg-card"}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs text-muted-foreground">{formatSupplierAgreementDate(agreement.startDate)}</p><h2 className="mt-1 truncate font-semibold">{vendorName}</h2><p className="mt-1 break-words text-sm text-muted-foreground">{materials}</p></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-medium ${agreement.isDeleted ? "bg-destructive/10 text-destructive" : agreement.status === "ACTIVE" ? "bg-emerald-500/10 text-emerald-700" : "bg-muted text-muted-foreground"}`}>{agreement.isDeleted ? "Deleted" : SUPPLIER_AGREEMENT_STATUS_LABELS[agreement.status]}</span></div><div className="mt-4 border-t pt-3"><p className="text-xs text-muted-foreground">Advance amount</p><p className="mt-1 text-xl font-semibold">{formatSupplierAgreementCurrency(agreement.advanceAmount)}</p>{agreement.notes && <p className="mt-2 line-clamp-2 break-words text-sm text-muted-foreground">{agreement.notes}</p>}</div><div className="mt-3 flex flex-wrap items-center justify-end gap-1 border-t pt-2"><button type="button" onClick={() => onDetails(agreement)} className="inline-flex min-h-10 items-center gap-1 rounded-lg px-3 text-sm hover:bg-muted"><Eye className="h-4 w-4" />View</button>{agreement.isDeleted ? <button type="button" disabled={isRestoring} onClick={() => onRestore(agreement)} className="inline-flex min-h-10 items-center gap-1 rounded-lg px-3 text-sm text-primary hover:bg-primary/10 disabled:opacity-50"><RotateCcw className="h-4 w-4" />{isRestoring ? "Restoring…" : "Restore"}</button> : <><button type="button" onClick={() => onEdit(agreement)} aria-label={`Edit supplier agreement for ${vendorName}`} className="flex h-10 w-10 items-center justify-center rounded-lg hover:bg-muted"><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => onDelete(agreement)} aria-label={`Delete supplier agreement for ${vendorName}`} className="flex h-10 w-10 items-center justify-center rounded-lg text-destructive hover:bg-destructive/10"><Trash2 className="h-4 w-4" /></button></>}</div></article>;
}
