import { useSupplierAgreementQuery, useSupplierAgreementSummaryQuery } from "@/features/supplier-agreements/supplier-agreement.queries";
import { SUPPLIER_AGREEMENT_BALANCE_LABELS, SUPPLIER_AGREEMENT_STATUS_LABELS, formatSupplierAgreementCurrency, formatSupplierAgreementDate } from "@/features/supplier-agreements/supplier-agreement.utils";
import type { SupplierAgreement } from "@/features/supplier-agreements/supplier-agreement.types";
import { LoaderCircle, Pencil, RotateCcw, Trash2, X } from "lucide-react";
import type { Vendor } from "@/features/vendors/vendor.types";
import type { Material } from "@/features/materials/material.types";

interface Props { agreement: SupplierAgreement | null; vendors: Vendor[]; materials: Material[]; isRestoring: boolean; onClose: () => void; onEdit: (agreement: SupplierAgreement) => void; onDelete: (agreement: SupplierAgreement) => void; onRestore: (agreement: SupplierAgreement) => void }
function errorMessage(error: unknown, fallback: string) { if (typeof error === "object" && error !== null && "response" in error) { const response = (error as { response?: { data?: { message?: string } } }).response; if (response?.data?.message) return response.data.message; } return error instanceof Error ? error.message : fallback; }
function Info({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl bg-muted/50 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 break-words text-sm font-medium">{value}</p></div>; }

export default function SupplierAgreementDetailsDialog({ agreement, vendors, materials, isRestoring, onClose, onEdit, onDelete, onRestore }: Props) {
  const detail = useSupplierAgreementQuery(agreement?.id ?? "", agreement?.isDeleted ?? false);
  const summary = useSupplierAgreementSummaryQuery(agreement?.id ?? "", Boolean(agreement && !agreement.isDeleted));
  if (!agreement) return null;
  const item = detail.data?.data ?? agreement;
  const vendorName = vendors.find((vendor) => vendor._id === item.vendorId)?.name ?? "Vendor no longer active";
  const materialNames = item.materialIds.map((id) => materials.find((material) => material._id === id)?.name ?? "Material no longer active");

  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 p-0 sm:items-center sm:p-4" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section role="dialog" aria-modal="true" aria-labelledby="supplier-agreement-details-title" className="max-h-[92vh] w-full overflow-y-auto rounded-t-2xl border bg-card p-5 shadow-xl sm:max-w-2xl sm:rounded-2xl"><header className="flex items-start justify-between gap-4"><div><p className="text-sm text-muted-foreground">{item.isDeleted ? "Deleted Supplier Agreement" : "Supplier Agreement details"}</p><h2 id="supplier-agreement-details-title" className="mt-1 text-xl font-semibold">{vendorName}</h2></div><button type="button" aria-label="Close details" onClick={onClose} className="rounded-lg p-2 hover:bg-muted"><X className="h-5 w-5" /></button></header>
    {detail.isLoading ? <div role="status" className="flex items-center justify-center gap-2 py-12 text-sm text-muted-foreground"><LoaderCircle className="h-4 w-4 animate-spin" />Loading agreement details…</div> : detail.isError ? <div role="alert" className="mt-4 rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm">{errorMessage(detail.error, "Unable to load agreement details.")} <button type="button" onClick={() => void detail.refetch()} className="ml-1 underline">Retry</button></div> : <>
      <div className="mt-5 grid gap-3 sm:grid-cols-2"><Info label="Vendor" value={vendorName} /><Info label="Materials" value={materialNames.join(", ") || "None"} /><Info label="Advance amount" value={formatSupplierAgreementCurrency(item.advanceAmount)} /><Info label="Start date" value={formatSupplierAgreementDate(item.startDate)} /><Info label="Status" value={item.isDeleted ? "Deleted" : SUPPLIER_AGREEMENT_STATUS_LABELS[item.status]} /><Info label="Created" value={formatSupplierAgreementDate(item.createdAt)} /><Info label="Last updated" value={formatSupplierAgreementDate(item.updatedAt)} /></div>
      {item.notes && <div className="mt-4"><h3 className="text-sm font-semibold">Notes</h3><p className="mt-1 whitespace-pre-wrap break-words text-sm text-muted-foreground">{item.notes}</p></div>}
      {!item.isDeleted && <section className="mt-5 rounded-2xl border p-4"><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold">Financial Summary</h3><p className="text-xs text-muted-foreground">Based on linked payments and material receipts.</p></div>{summary.isFetching && <LoaderCircle className="h-4 w-4 animate-spin text-muted-foreground" />}</div>{summary.isLoading ? <div role="status" className="flex items-center gap-2 py-6 text-sm text-muted-foreground"><LoaderCircle className="h-4 w-4 animate-spin" />Loading financial summary…</div> : summary.isError ? <div role="alert" className="mt-3 text-sm text-destructive">{errorMessage(summary.error, "Unable to load financial summary.")} <button type="button" onClick={() => void summary.refetch()} className="underline">Retry</button></div> : summary.data && <><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3"><Info label="Agreement advance" value={formatSupplierAgreementCurrency(summary.data.data.financials.agreementAdvanceAmount)} /><Info label="Total paid" value={formatSupplierAgreementCurrency(summary.data.data.financials.totalPaid)} /><Info label="Total material received" value={formatSupplierAgreementCurrency(summary.data.data.financials.totalMaterialReceived)} /><Info label="Balance" value={formatSupplierAgreementCurrency(summary.data.data.financials.balance)} /><Info label="Balance type" value={SUPPLIER_AGREEMENT_BALANCE_LABELS[summary.data.data.financials.balanceType]} /></div><div className="mt-4"><h4 className="text-sm font-semibold">Activity Counts</h4><div className="mt-2 grid grid-cols-2 gap-3"><Info label="Payment count" value={String(summary.data.data.counts.paymentCount)} /><Info label="Material receipt count" value={String(summary.data.data.counts.materialReceiptCount)} /></div></div></>}</section>}
      <div className="mt-5 flex flex-wrap justify-end gap-2 border-t pt-4">{item.isDeleted ? <button type="button" disabled={isRestoring} onClick={() => onRestore(item)} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-primary px-4 text-sm text-primary-foreground"><RotateCcw className="h-4 w-4" />{isRestoring ? "Restoring…" : "Restore"}</button> : <><button type="button" onClick={() => onEdit(item)} className="inline-flex min-h-10 items-center gap-2 rounded-xl border px-4 text-sm"><Pencil className="h-4 w-4" />Edit</button><button type="button" onClick={() => onDelete(item)} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-destructive/30 px-4 text-sm text-destructive"><Trash2 className="h-4 w-4" />Delete</button></>}</div>
    </>}
  </section></div>;
}
