import { Filter, X } from "lucide-react";
import { SUPPLIER_AGREEMENT_STATUS } from "@/features/supplier-agreements/supplier-agreement.types";
import { SUPPLIER_AGREEMENT_STATUS_LABELS } from "@/features/supplier-agreements/supplier-agreement.utils";
import type { Vendor } from "@/features/vendors/vendor.types";

export interface SupplierAgreementFilterValues { vendorId: string; status: string }
interface Props { values: SupplierAgreementFilterValues; vendors: Vendor[]; includeDeleted: boolean; onChange: (key: keyof SupplierAgreementFilterValues, value: string) => void; onDeletedChange: (value: boolean) => void; onClear: () => void }
const selectClass = "mt-1.5 h-11 w-full min-w-0 rounded-xl border bg-background px-3 text-sm font-normal";

export default function SupplierAgreementFilters({ values, vendors, includeDeleted, onChange, onDeletedChange, onClear }: Props) {
  const hasFilters = Boolean(values.vendorId || values.status || includeDeleted);
  return <section aria-label="Supplier Agreement filters" className="rounded-2xl border bg-card p-4 shadow-sm"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-muted"><Filter className="h-4 w-4" /></span><div><h2 className="text-sm font-semibold">Filter agreements</h2><p className="text-xs text-muted-foreground">Narrow by supplier or agreement status.</p></div></div>{hasFilters && <button type="button" onClick={onClear} className="inline-flex min-h-10 items-center gap-1.5 rounded-xl px-2.5 text-xs font-medium text-muted-foreground hover:bg-muted"><X className="h-3.5 w-3.5" />Clear</button>}</div><div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2"><label className="text-xs font-medium">Vendor<select aria-label="Filter by vendor" value={values.vendorId} onChange={(event) => onChange("vendorId", event.target.value)} className={selectClass}><option value="">All vendors</option>{vendors.map((vendor) => <option key={vendor._id} value={vendor._id}>{vendor.name}</option>)}</select></label><label className="text-xs font-medium">Status<select aria-label="Filter by status" value={values.status} onChange={(event) => onChange("status", event.target.value)} className={selectClass}><option value="">All statuses</option>{Object.values(SUPPLIER_AGREEMENT_STATUS).map((status) => <option key={status} value={status}>{SUPPLIER_AGREEMENT_STATUS_LABELS[status]}</option>)}</select></label></div><div className="mt-4 border-t pt-3"><label className="inline-flex min-h-10 cursor-pointer items-center gap-2 text-sm"><input type="checkbox" checked={includeDeleted} onChange={(event) => onDeletedChange(event.target.checked)} className="h-4 w-4 accent-primary" />Show deleted agreements only</label></div></section>;
}
