import { AlertTriangle, Loader2, X } from "lucide-react";
import type { Payment } from "@/features/payments/payment.types";

interface Props { payment: Payment | null; isDeleting: boolean; onConfirm: () => void; onClose: () => void; }

export default function PaymentDeleteDialog({ payment, isDeleting, onConfirm, onClose }: Props) {
  if (!payment) return null;
  return <div className="fixed inset-0 z-[60] flex items-end justify-center bg-black/40 p-0 sm:items-center sm:p-4" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !isDeleting) onClose(); }}><section role="alertdialog" aria-modal="true" aria-labelledby="payment-delete-title" aria-describedby="payment-delete-description" className="w-full rounded-t-2xl border bg-card p-5 shadow-xl sm:max-w-md sm:rounded-2xl"><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-destructive/10"><AlertTriangle className="h-5 w-5 text-destructive" /></span><div><h2 id="payment-delete-title" className="font-semibold">Remove {payment.paymentNo}?</h2><p id="payment-delete-description" className="mt-1 text-sm text-muted-foreground">This payment will be removed from the active list. You can restore it afterward.</p></div></div><button type="button" aria-label="Close dialog" disabled={isDeleting} onClick={onClose} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg hover:bg-muted"><X className="h-5 w-5" /></button></div><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" disabled={isDeleting} onClick={onClose} className="min-h-11 rounded-lg border px-4 text-sm font-medium hover:bg-muted">Cancel</button><button type="button" disabled={isDeleting} onClick={onConfirm} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-destructive px-4 text-sm font-medium text-destructive-foreground">{isDeleting && <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />}{isDeleting ? "Removing…" : "Remove payment"}</button></div></section></div>;
}
