import { useContractQuery, useContractSummaryQuery } from "@/features/contracts/contract.queries";
import type { Contract } from "@/features/contracts/contract.types";
import { CONTRACT_RATE_UNIT_LABELS, CONTRACT_STATUS_LABELS, CONTRACT_TYPE_LABELS, formatContractCurrency, formatContractDate } from "@/features/contracts/contract.utils";
import { LoaderCircle, Pencil, RotateCcw, Trash2, X } from "lucide-react";
interface Props { contract: Contract | null; vendorName: string; isRestoring: boolean; onClose: () => void; onEdit: (contract: Contract) => void; onDelete: (contract: Contract) => void; onRestore: (contract: Contract) => void }
function message(error: unknown, fallback: string) { if (typeof error === "object" && error !== null && "response" in error) { const response = (error as { response?: { data?: { message?: string } } }).response; if (response?.data?.message) return response.data.message; } return fallback; }
function Info({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl bg-muted/50 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 break-words text-sm font-medium">{value}</p></div>; }
function ScopeList({ title, items }: { title: string; items: string[] }) { return <div><h3 className="text-sm font-semibold">{title}</h3>{items.length ? <ul className="mt-2 list-inside list-disc space-y-1 text-sm text-muted-foreground">{items.map((item, index) => <li key={`${item}-${index}`} className="break-words">{item}</li>)}</ul> : <p className="mt-1 text-sm text-muted-foreground">None specified</p>}</div>; }
export default function ContractDetailsDialog({ contract, vendorName, isRestoring, onClose, onEdit, onDelete, onRestore }: Props) {
 const detail = useContractQuery(contract?.id ?? "", contract?.isDeleted ?? false); const summary = useContractSummaryQuery(contract?.id ?? "", Boolean(contract && !contract.isDeleted));
 if (!contract) return null;
 const item = detail.data?.data ?? contract;
 return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 p-0 sm:items-center sm:p-4" role="presentation" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}><section role="dialog" aria-modal="true" aria-labelledby="contract-details-title" className="max-h-[92vh] w-full overflow-y-auto rounded-t-2xl border bg-card p-5 shadow-xl sm:max-w-2xl sm:rounded-2xl"><header className="flex items-start justify-between gap-4"><div><p className="text-sm text-muted-foreground">{item.isDeleted ? "Deleted contract" : "Contract details"}</p><h2 id="contract-details-title" className="mt-1 text-xl font-semibold">{vendorName}</h2></div><button type="button" aria-label="Close details" onClick={onClose} className="rounded-lg p-2 hover:bg-muted"><X className="h-5 w-5" /></button></header>
 {detail.isLoading ? <div role="status" className="flex items-center justify-center gap-2 py-12 text-sm text-muted-foreground"><LoaderCircle className="h-4 w-4 animate-spin" />Loading contract details…</div> : detail.isError ? <div role="alert" className="mt-4 rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm">{message(detail.error, "Unable to load contract details.")} <button type="button" onClick={() => void detail.refetch()} className="ml-1 underline">Retry</button></div> : <><div className="mt-5 grid gap-3 sm:grid-cols-2"><Info label="Type" value={CONTRACT_TYPE_LABELS[item.contractType]} /><Info label="Status" value={CONTRACT_STATUS_LABELS[item.status]} /><Info label="Rate" value={`${formatContractCurrency(item.rate)} / ${CONTRACT_RATE_UNIT_LABELS[item.rateUnit]}`} /><Info label="Measurement" value={item.measurement === null ? "Not applicable" : String(item.measurement)} /><Info label="Estimated value" value={formatContractCurrency(item.estimatedAmount)} /><Info label="Advance" value={formatContractCurrency(item.advanceAmount)} /><Info label="Start date" value={formatContractDate(item.startDate)} /></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><ScopeList title="Included scope" items={item.scopeIncluded} /><ScopeList title="Excluded scope" items={item.scopeExcluded} /></div>{item.notes && <div className="mt-4"><h3 className="text-sm font-semibold">Notes</h3><p className="mt-1 whitespace-pre-wrap text-sm text-muted-foreground">{item.notes}</p></div>}
 {!item.isDeleted && <section className="mt-5 rounded-2xl border p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">Financial summary</h3>{summary.isFetching && <LoaderCircle className="h-4 w-4 animate-spin text-muted-foreground" />}</div>{summary.isLoading ? <div role="status" className="flex items-center gap-2 py-5 text-sm text-muted-foreground"><LoaderCircle className="h-4 w-4 animate-spin" />Loading financial summary…</div> : summary.isError ? <div role="alert" className="mt-3 text-sm text-destructive">{message(summary.error, "Unable to load financial summary.")} <button type="button" onClick={() => void summary.refetch()} className="underline">Retry</button></div> : summary.data && <><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4"><Info label="Total paid" value={formatContractCurrency(summary.data.data.financials.totalPaid)} /><Info label="Remaining" value={formatContractCurrency(summary.data.data.financials.remainingBalance)} /><Info label="Payments" value={String(summary.data.data.financials.paymentCount)} /><Info label="Paid" value={`${summary.data.data.financials.paymentPercentage}%`} /></div><div className="mt-4 space-y-2">{summary.data.data.payments.map((payment) => <div key={payment.id} className="flex flex-wrap justify-between gap-2 border-t pt-2 text-sm"><span>{payment.paymentNo} · {formatContractDate(payment.date)}</span><span className="font-medium">{formatContractCurrency(payment.amount)}</span></div>)}{summary.data.data.payments.length === 0 && <p className="border-t pt-3 text-sm text-muted-foreground">No payments recorded against this contract.</p>}</div></>}</section>}
 <div className="mt-5 flex flex-wrap justify-end gap-2 border-t pt-4">{item.isDeleted ? <button type="button" disabled={isRestoring} onClick={() => onRestore(item)} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-primary px-4 text-sm text-primary-foreground"><RotateCcw className="h-4 w-4" />{isRestoring ? "Restoring…" : "Restore"}</button> : <><button type="button" onClick={() => onEdit(item)} className="inline-flex min-h-10 items-center gap-2 rounded-xl border px-4 text-sm"><Pencil className="h-4 w-4" />Edit</button><button type="button" onClick={() => onDelete(item)} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-destructive/30 px-4 text-sm text-destructive"><Trash2 className="h-4 w-4" />Delete</button></>}</div></>}
 </section></div>;
}
